### ISSUE TITLE
API change regarding authentication

### ISSUE THREAD

**Issue by jasonbphillips** [elliotchance/independentreserve#14]
On April 15, 2018, a change in the Independent Reserve Airbridge API removed support for the method of authentication used in v1.1.3 and prior versions of the PHP client.

Authentication using a signature generated with only a nonce and user API key is no longer accepted. Requests to private methods of the API using a signature generated in that way produce a "400 Invalid credentials" error.

Requests to public methods of the API are unaffected.

The current method of generating a signature for authentication to the API is detailed at:

https://www.independentreserve.com/API

**Comment by elliotchance** [comment]
Thanks for raising this, do you have a PR to follow?

**Comment by MaxPovver** [comment]
@elliotchance  I'll make one for you because your repo is first when searching for this api :)

**Comment by elliotchance** [comment]
@jasonbphillips I have merged in @MaxPovver's fix, does this also fix it for you?

**Comment by jasonbphillips** [comment]
Thanks Elliot. It does fix my particular use case and follows the general pattern I was mulling over. My initial thought, though, is that this fix doesn't ensure that parameters are passed in the particular order that the API documentation says is required for each particular private endpoint. I haven't tested to see that the system enforces that particular point, however...

**Comment by MaxPovver** [comment]
@jasonbphillips I tried different order of parameters, it still worked, I think their api docs are not 100% up to date.

**Comment by elliotchance** [comment]
Awesome! I will close this now.
