### ISSUE TITLE
Update PHP version requirement

### ISSUE THREAD

**Issue by haydenw** [elliotchance/independentreserve#8]
Assuming this is compatible with newer versions on PHP (in my case 5.6.3) could you please update your composer.json and packagist listing. When trying to require in my project I get the following message:
`This package requires php 5.4.* but your PHP version (5.6.3) does not satisfy that requirement.`

Thanks

**Comment by elliotchance** [comment]
Hm, strange. Are you sure the error is coming from this package? The requirement is `>=5.4`...

**Comment by haydenw** [comment]
Ah yes was another package. Sorry about that!

**Comment by elliotchance** [comment]
No worries :+1:
